### PR TITLE
Pull Request (8) - User manage events

### PR DESCRIPTION
**Pull request by johnsonsirv**
***User Auth***
```User``` registers a unique **username** and **fullname**
```User``` can login with ```username```
All feature and unit tests validating this feature pass

***Associations***
Set up models using ERD - for ```User```, ```Event```
Complete model relationships using ERD cardinality => ``1 : M``, ``M : M``
```User``` has many created ```Events```  / ```Event``` has a creator(***User***)
```Event``` has many attendees(***User***)   /  ```User``` has many attendable ```Events```
All model query through associations unit tests  pass

***User and Events***
A registered ```User``` can create a new ```Event```, and will automatically become an event attendee
A ```User``` can attend/cancel an event/event attendance
A ```User``` can view all lists of ```Events``` or views details of a single ```Event```
A ```User``` can see all ```Event```s they are attending
```Event```s display as ``Upcoming`` or ``Past`` depending on the event date.
``Past`` events can no longer be ***attendable*** or ***cancelled***
All feature and unit tests validating this feature pass

***Suggested Features / Requirements from PR review***
Added feature/unit tests for suggested requirements - 
---- ```validate past event date```, 
---- display ```created```, ```upcoming```, ```past``` events on the user page
---- display ```attendees``` on event details page

Made test case pass, implemented all suggested features

***Suggested Review***
--- update ```stickler```

Kindly review new PR

### CODE REVIEW

**Comment by johnsonsirv** [comment]
Thank you @efrapp  for the review. Please could you explain a little bit more about what you mean in the first point about "validations are red"
Thank you for the review

**Comment by johnsonsirv** [comment]
> * [ ]  Please, fix it is the validations are red. Also, if you get the same error as me, please, put a comment about that in the description, to alert future reviewers.

@efrapp  Please shed some light here, what you mean

**Comment by efrapp** [comment]
Sorry @johnsonsirv it was a type, I wanted to say: fix it **if** the validations are red

**Comment by efrapp** [comment]
I can't check if they are red or green because of the image I put above. If they are green, it is ok but if they are red, please, fix them.

**Comment by johnsonsirv** [comment]
I am also getting the same image when I checked.

**Comment by johnsonsirv** [comment]
> * [ ]  Pass your logic in the `session_helper.rb` to the `application_controller.rb`. Helpers shouldn't have logic on them. Check this: http://codefol.io/posts/Where-Do-I-Put-My-Code/

@efrapp what logic in the ```session_helper``` are you exactly referring to? because the article you sent to me also acknowledges that some ```logic``` corresponding to views can also be in ``methods`` within view ```helpers``` (from my own understanding) 
Are you are referring to the ``require_login`` method or which?

**Comment by johnsonsirv** [comment]
@adriaanbd Thank you for the review. 

My project already has unit tests in RSpec and integration level tests with Cucumber/capybara/Rspec. Kindly refer to my```specs``` and ```features``` directories.
I also included information how to run the tests on my ```Readme.md```

Kindly re-review

**Comment by adriaanbd** [comment]
@johnsonsirv Integration tests are not the same as feature or UI tests. 

This project has no integration tests (controller specs or request specs) and the unit tests that are provided are exclusively testing validations; there are no tests for associations or record creation. There should at least be validations and associations at the unit test level.

**Comment by johnsonsirv** [comment]
> @johnsonsirv Integration tests are not the same as feature or UI tests.
> 
> This project has no integration tests (controller specs or request specs) and the unit tests that are provided are exclusively testing validations; there are no tests for associations or record creation. There should at least be validations and associations at the unit test level.
> 
> Kindly refer to the **Tests** snippet provided above:
> 
> * models have unit tests for validations **and associations**
> * authentication has **integration tests**
> * event management features have **integration tests**

Thanks @adriaanbd for the review. 

Kindly provide me with resources where I can learn about the differences between integration tests and feature tests. 

I understand controller tests and I also understand request test as different forms of integration level testing. 
Yes,  from my project I implemented  integration testing.
Supposedly I also need to implement unit tests for "associations", and "controller/request" tests using Rspec and Cabybara?

**Comment by adriaanbd** [comment]
@johnsonsirv the terminology is quite confusing and it depends on the testing framework. The feature specs that you have are end-to-end testing, that test the application through the browser, simulating the behaviour of a real user. I refer to those as feature tests or UI tests. Now a days, I understand request specs are favoured over controller specs, and they test the app from a HTTP to Models level, which is everything that the user does not see. My understanding of integration tests would imply request specs, but considering that the requirements have Rspec and Capybara in parenthesis, I think is safe to assume that integration tests in this context imply feature / UI / end-to-end tests, as that is what Capybara is used for. Therefore, the only real hard requirement missing here is the addition of Unit tests for associations for all of your models, which you have added in a recent commit for Event and User [here](https://github.com/johnsonsirv/private-event/pull/8/commits/c40c80ec32ccfaa915a44e7f306f415c6f96f101).

**Comment by johnsonsirv** [comment]
Thank you @adriaanbd for your succinct explanation.

This is clearer to me now, and I think we both have a common perspective on this. 

Thank you for your time.

**Comment by azdrenymeri** [comment]
### Hello @johnsonsirv 
#### Tests are adjusted  and passing 👏 
##### You can merge it and move on 👍

**Comment by johnsonsirv** [comment]
> ### Hello @johnsonsirv
> #### Tests are adjusted and passing 
> ##### You can merge it and move on

Thank you @azdrenymeri for your review.

**Pull request merged**
